### PR TITLE
Fixes #32709 - Drop all code related to ansible-playbook

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
This should work on its own, but needs theforeman/foreman-tasks#666 to work with batch triggering turned off

**Comment by ezr-ondrej** [comment]
The tasks PR is in, so now we need to release tasks and depend on the new version in this PR?

**Comment by adamruzicka** [comment]
We can't really depend from smart_proxy_ansible on foreman-tasks. They might even be installed on different machines.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @adamruzicka ! :+1: I've branched 3.3-stable prior this change and 3.4 should target Foreman 3.2 :)

**Pull request merged**
