### PR TITLE
Remove foreman_ansible_core leftover

### PR DESCRIPTION
**Pull request by ekohl**
850db0b63a813fe39ce186360d8291f3f7b3e819 removed the plugin but left this.

### CODE REVIEW

**Comment by ekohl** [comment]
Note I'm not 100% sure this is correct but it seems to me we should retire `foreman_ansible_core`. If it's needed by the smart proxy to run in the `_core` context I think we should create `smart_proxy_ansible_core` instead.

**Comment by ares** [comment]
@aruzicka please keep me honest here but I think smart_proxy_ansible needs foreman_ansible_core. This contains "how to actucally run foreman ansible" so e.g. logic of how to build "ansible-playbook" command. It lives in foreman_ansible repo, because it shares/d some definitions. I don't know if we still need this, but the same pattern is there for rex, tasks and dynflow, so I'd prefer avoid renaming just one gem.

**Comment by ekohl** [comment]
I think you're right, but it's weird that smart_proxy_ansible is the only consumer of foreman_ansible_core. Having smart_proxy_ansible_core makes more sense. That can then still be shipped as tfm-rubygem-smart_proxy_ansible_core so dynflow can load it.

**Comment by ares** [comment]
I agree and would be happy if someone does the renaming. Anyway, I'm closing this for now.

**Pull request closed without merging**
