### PR TITLE
Fixes #30249 - Add roles from collection

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by xprazak2** [comment]
Seems like the failures are not directly related to the changes, but it is a lot of failures. Any chance they can be fixed to see if the new code breaks anything?

Would it make sense to pull the original commit from https://github.com/theforeman/smart_proxy_ansible/pull/22 and add commits with changes on top of it so that the community member who opened the original PR gets the contribution?

**Comment by ezr-ondrej** [comment]
@shiramax what's the status? :)
Needs rebase and @xprazak2's query about the original authors commit is still unanswered.
FWIW I agree it would be great to honour the original contribution and base it on that commit, if there is at least some value in it.

**Comment by shiramax** [comment]
@ezr-ondrej I'm just fixing the tests, and yes I wasn't able to commit on the original PR, it might be a permissions issue? but sure I will fix it and stick to the original PR

**Comment by ezr-ondrej** [comment]
> @ezr-ondrej I'm just fixing the tests, and yes I wasn't able to commit on the original PR, it might be a permissions issue? but sure I will fix it and stick to the original PR

probably permissions, but new PR is not an issue, just use the commit that has been presented in the other PR :)

**Pull request closed without merging**
