### PR TITLE
Fixes #26970 - Enhance default path for roles import

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
test failures related
```

  1) Failure:
#roles_path#test_detects_commented_roles_path [/home/travis/build/theforeman/smart_proxy_ansible/test/roles_reader_test.rb:20]:
--- expected
+++ actual
@@ -1 +1 @@
-"/etc/ansible/roles"
+"/etc/ansible/roles:/usr/share/ansible/roles"
  2) Failure:
#roles_path#test_returns_default_path_if_no_roles_path_defined [/home/travis/build/theforeman/smart_proxy_ansible/test/roles_reader_test.rb:26]:
--- expected
+++ actual
@@ -1 +1 @@
-"/etc/ansible/roles"
+"/etc/ansible/roles:/usr/share/ansible/roles"

```

**Comment by ares** [comment]
I was under the impression installer configured these directories in ansible.cfg - https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/plugin/ansible/params.pp#L5

this ansible.cfg should work under foreman-proxy user, did you have a chance to find out, why it does not work?

**Comment by xprazak2** [comment]
Because `RolesReader` does not use /usr/share/ansible/ansible.cfg at all, but tries to get roles path from [/etc/ansible/ansible.cfg](https://github.com/theforeman/smart_proxy_ansible/blob/master/lib/smart_proxy_ansible/roles_reader.rb#L8) or defaults to [preconfigured paths]()

**Comment by xprazak2** [comment]
I removed the bundler version constraint from gemspec so that we could bundle, all green now.

**Comment by ares** [comment]
As we agreed, the follow up should be that the roles reader will look at smart_proxy_ansible configuration that will contain new `roles_path` option. That should be set by the installer which also sets it in https://github.com/theforeman/puppet-foreman_proxy/blob/master/templates/plugin/ansible.cfg.erb

That way when we run ansible, it will use the same roles that we imported in Foreman.

That however does not block this workaround for the moment, so merging. Thanks @xprazak2, merging!

**Pull request merged**
