### PR TITLE
Fixes #16506 - Version 1.0.0 of the plugin

### PR DESCRIPTION
**Pull request by dLobatog**
Updated the README to reflect the new nature of the project. 

@iNecas if you can merge this, I'll make the gem, submit the packaging PRs, etc...

### CODE REVIEW

**Comment by iNecas** [comment]
I would love to, but not having merge permissions :( It's not in rubygems just yet, so whoever does the push wins the the first owner permissions :) I will be happy to work on packaging

**Comment by dLobatog** [comment]
Oh it's fine then. I'll merge it, @ohadlevy or @domcleal can you give @iNecas permissions to merge here? I'll take care of the release

**Comment by domcleal** [comment]
@dLobatog you should be able to manage that via https://github.com/orgs/theforeman/teams/ansible

**Comment by dLobatog** [comment]
Oh didn't know I could add people to that. @iNecas feel free to check the README and point any mistakes before merging :smile: 

I'll create the gem in rubygems and add you there as maintainer too.

**Comment by iNecas** [comment]
Thanks @dLobatog

**Pull request merged**
