### PR TITLE
Remove Travis, fix tests

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Though I am not sure why we tested on both travis and jenkins...

**Comment by ezr-ondrej** [comment]
Do we use/want to use rubocop? ... if not, we do not need to test on GH actions. Jenkins would be enough.
I think we were testing on Travis because Jenkins didn't work, but Ewoud fixed it.

**Comment by xprazak2** [comment]
We can add GH actions with rubocop job if we decide to use it. I changed this to remove Travis and fix tests.

**Review by ezr-ondrej — APPROVED** [review]
Thanks @xprazak2 ! :)

**Pull request merged**
