### PR TITLE
Refs #36130 - Update code for compatibility with Ansible 2.12.2

### PR DESCRIPTION
**Pull request by nofaralfasi**
Set the exit status to success only for rescued tasks.

### CODE REVIEW

**Comment by adamruzicka** [comment]
> While this PR solves this for most Ansible versions, in Ansible 2.12.2 this scenario has a different behavior:

Do I read it right that if there's a missing module being used, then newer ansible will refuse to run the entire playbook?

**Comment by nofaralfasi** [comment]
> > While this PR solves this for most Ansible versions, in Ansible 2.12.2 this scenario has a different behavior:
> 
> Do I read it right that if there's a missing module being used, then newer ansible will refuse to run the entire playbook?

Correct. For example: 
image

**Comment by adamruzicka** [comment]
How would going with what you proposed as option 1 fix it?

**Comment by adamruzicka** [comment]
Oh, right. Still, that's not really nice. I'd lean towards option 2

**Comment by nofaralfasi** [comment]
Thanks @adamruzicka!
Created this issue https://projects.theforeman.org/issues/36210 as a follow-up.

**Review by adamruzicka — APPROVED** [review]
Same as with the previous iteration, it seems to work in a couple of cases I've tried, but I can't really envision all the edge cases that can happen.

**Pull request merged**
